export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const RootLayout = async ({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: "en" | "ru" | "hy" };
}) => {
  return (
    <html lang={params.locale}>
      <body>{children}</body>
    </html>
  );
};
